// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package productcatalogmodule.actions;

import com.mendix.core.Core;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixIdentifier;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import com.mendix.systemwideinterfaces.core.UserAction;
import com.mendix.systemwideinterfaces.connectionbus.data.IDataTable;
import com.mendix.systemwideinterfaces.connectionbus.data.IDataRow;
import java.util.*;

public class JA_GetGanttNodes extends UserAction<java.util.List<IMendixObject>>
{
	public JA_GetGanttNodes(IContext context)
	{
		super(context);
	}

	@java.lang.Override
	public java.util.List<IMendixObject> executeAction() throws Exception
	{
		// BEGIN USER CODE
        IContext context = getContext();

        // ── 1. Build & execute OQL (flat join: Variant × Product × Category) ──
        String oql = buildOqlQuery();
        IDataTable dataTable = Core.retrieveOQLDataTable(context, oql);

        List<IMendixObject> result = new ArrayList<>();
        Set<Long> seenCategories = new HashSet<>();
        Set<Long> seenProducts   = new HashSet<>();

        // ── 2. Iterate rows via IDataRow → build hierarchy ──
        // Mendix OQL "Entity.id" returns MendixIdentifier, NOT Long.
        // Use getId(row, ctx, "ColumnName") to extract the Long value.

        for (IDataRow row : dataTable) {
            Long   categoryId     = getId(row, context, "Category_Id");
            String categoryName   = getString(row, context, "Category_Name");
            Long   productId      = getId(row, context, "Product_Id");
            String productName    = getString(row, context, "Product_Name");
            String productCode    = getString(row, context, "Product_Code");
            Date   productCreated = getDate(row, context, "Product_CreatedDateAt");
            Long   variantId      = getId(row, context, "Variant_Id");
            String variantSku     = getString(row, context, "Variant_SKU");
            String variantColor   = getString(row, context, "Variant_Color");
            String variantSize    = getString(row, context, "Variant_Size");
            String variantNote    = getString(row, context, "Variant_Note");
            Date   variantStart   = getDate(row, context, "Variant_StartDate");
            Date   variantEnd     = getDate(row, context, "Variant_EndDate");

            // ── Category node (root level, once per unique category) ──
            if (categoryId != null && !seenCategories.contains(categoryId)) {
                seenCategories.add(categoryId);
                result.add(createGanttNode(context,
                        categoryId, 0L, categoryName, "Category",
                        null, null, null, null));
            }

            // ── Product node (once per unique product) ──
            if (productId != null && !seenProducts.contains(productId)) {
                seenProducts.add(productId);
                result.add(createGanttNode(context,
                        productId, categoryId, productName, "Product",
                        productCreated, null, null, productCode));
            }

            // ── Variant node (every row becomes a leaf) ──
            String displayName = buildVariantName(variantSku, variantColor, variantSize);
            result.add(createGanttNode(context,
                    variantId, productId, displayName, "Variant",
                    variantStart, variantEnd, variantNote, variantSku));
        }

        return result;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "JA_GetGanttNodes";
	}

	// BEGIN EXTRA CODE
    // ══════════════════════════════════════════════════════════════════════════
    //  OQL — flat join query
    // ══════════════════════════════════════════════════════════════════════════

    private String buildOqlQuery() {
        return
                "SELECT " +
                        "  C.id            AS Category_Id, " +
                        "  C.Name          AS Category_Name, " +
                        "  C.SortOrder     AS Category_SortOrder, " +
                        "  P.id            AS Product_Id, " +
                        "  P.Name          AS Product_Name, " +
                        "  P.Code          AS Product_Code, " +
                        "  P.CreatedDateAt AS Product_CreatedDateAt, " +
                        "  PV.id           AS Variant_Id, " +
                        "  PV.SKU          AS Variant_SKU, " +
                        "  PV.Color        AS Variant_Color, " +
                        "  PV.Size         AS Variant_Size, " +
                        "  PV.Price        AS Variant_Price, " +
                        "  PV.StockQty     AS Variant_StockQty, " +
                        "  PV.SoldQty      AS Variant_SoldQty, " +
                        "  PV.Note         AS Variant_Note, " +
                        "  PV.StartDate    AS Variant_StartDate, " +
                        "  PV.EndDate      AS Variant_EndDate " +
                        "FROM ProductCatalogModule.ProductVariant AS PV " +
                        "  JOIN PV/ProductCatalogModule.ProductVariant_Product/ProductCatalogModule.Product AS P " +
                        "  JOIN P/ProductCatalogModule.Product_Category/ProductCatalogModule.Category AS C " +
                        "WHERE PV.IsActive = true " +
                        "  AND P.IsActive = true " +
                        "  AND C.IsActive = true " +
                        "ORDER BY C.SortOrder, P.Name, PV.SKU";
    }

    // ══════════════════════════════════════════════════════════════════════════
    //  Helper: create a GanttNodeDTO IMendixObject
    // ══════════════════════════════════════════════════════════════════════════

    private IMendixObject createGanttNode(IContext ctx,
            Long nodeId, Long parentId, String name, String nodeType,
            Date startDate, Date endDate, String note, String sku) throws Exception {

        IMendixObject node = Core.instantiate(ctx, "ProductCatalogModule.GanttNodeDTO");
        node.setValue(ctx, "NodeID",   nodeId);
        node.setValue(ctx, "ParentId", parentId);
        node.setValue(ctx, "Name",     name     != null ? name     : "");
        node.setValue(ctx, "NodeType", nodeType != null ? nodeType : "");
        node.setValue(ctx, "StartDate", startDate);
        node.setValue(ctx, "EndDate",   endDate);
        node.setValue(ctx, "Note",      note);
        node.setValue(ctx, "SKU",       sku);
        return node;
    }

    // ══════════════════════════════════════════════════════════════════════════
    //  Helper: build variant display name  → "Color - Size" or SKU fallback
    // ══════════════════════════════════════════════════════════════════════════

    private String buildVariantName(String sku, String color, String size) {
        if (color != null && !color.isEmpty()) {
            if (size != null && !size.isEmpty()) {
                return color + " - " + size;
            }
            return color;
        }
        return sku != null ? sku : "";
    }

    // ══════════════════════════════════════════════════════════════════════════
    //  Helper: extract Long ID from OQL result
    //
    //  KEY INSIGHT: Mendix OQL "Entity.id" returns a MendixIdentifier
    //  object (e.g. "[MendixIdentifier:: id=1970324837064366 ...]"),
    //  NOT a Long. We must call .getId() to get the numeric value.
    //
    //  MendixIdentifier class: IMendixIdentifier in
    //    com.mendix.systemwideinterfaces.core.IMendixIdentifier
    //  Method: long getId() — returns the numeric database ID
    // ══════════════════════════════════════════════════════════════════════════

    private Long getId(IDataRow row, IContext ctx, String col) {
        Object val = row.getValue(ctx, col);
        if (val == null) return null;

        // OQL "Entity.id" → returns IMendixIdentifier
        if (val instanceof IMendixIdentifier) {
            return ((IMendixIdentifier) val).toLong();
        }
        // Fallback: numeric types
        if (val instanceof Long)   return (Long) val;
        if (val instanceof Number) return ((Number) val).longValue();
        return null;
    }

    // ══════════════════════════════════════════════════════════════════════════
    //  Helper: safe IDataRow value extraction for String and Date
    //  Mendix 10 API: <T> T getValue(IContext context, String columnName)
    // ══════════════════════════════════════════════════════════════════════════

    private String getString(IDataRow row, IContext ctx, String col) {
        Object val = row.getValue(ctx, col);
        return val != null ? val.toString() : null;
    }

    private Date getDate(IDataRow row, IContext ctx, String col) {
        Object val = row.getValue(ctx, col);
        if (val instanceof Date) return (Date) val;
        return null;
    }
	// END EXTRA CODE
}
